#!/usr/bin/env bash
# Local twin of this repo's ci-ansible.yml composer lint: runs ansible-lint
# over this repo's Ansible content (the root shim + the nested
# hyper-v/ubuntu/Ansible composer playbook) through the shared Common-Ansible
# controller venv, reusing the exact helper and config CI runs
# (Common-Ansible/.github/actions/ansible-lint/ansible-lint.sh) so the local
# pre-push bar cannot drift from CI's.
#
# Why this lives here and not in the delegated runner: feature 20 re-homed the
# Ansible gate from Common-Automation into Common-Ansible, and Common-
# Automation's delegated _run-lint-yaml-and-bash.sh no longer runs ansible-
# lint. Without this script a local lint run would skip ansible-lint entirely
# for this repo. Wired into run-lint-yaml-and-bash.sh.
#
# Composer role resolution. This repo ships NO roles of its own - its single
# playbook import_roles the Common-Ansible substrate roles (jdk, dotnet_sdk,
# dotnet_tools). So the substrate roles/ must be on ANSIBLE_ROLES_PATH for
# ansible-lint's syntax-check to resolve them, exactly as the reusable
# workflow's composes-substrate-roles branch does in CI. The root ansible.cfg
# shim carries no roles_path (and Ansible ignores an ansible.cfg on the
# world-writable /mnt/c drvfs mount anyway), so the env var is the single
# source of role resolution here - matching the substrate-only branch of
# Common-Ansible/ops/_ansible-env.sh (a consumer with no roles/ of its own).
#
# Execution model mirrors Common-Ansible's self runner: ansible-lint - and the
# bare `ansible-config` it shells out to - live in the WSL controller venv, not
# on Windows, so under Git Bash re-exec self inside the WSL default distro. The
# consumer owns no venv; it reuses the shared Common-Ansible controller (.venv)
# that ops/bootstrap-controller-consumer.sh locates-or-ensures. Auto-skips with
# a ::notice:: (exit 0) when that shared venv is absent so a host that never
# bootstrapped the controller still gets a green run; the helper owns the
# complementary no-Ansible-content auto-skip.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

# Windows launcher bridge - mirrors Common-Ansible/scripts/run-lint-ansible.sh
# and ops/_run-playbook.sh. See the header for why the venv is only reachable
# inside WSL.
case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*)
        if ! command -v wsl.exe >/dev/null 2>&1; then
            echo "::notice::launched under Git Bash but wsl.exe is unavailable; skipping ansible-lint (bootstrap the WSL controller to enable it)"
            exit 0
        fi
        # Translate this script's own dir /c/... (Git Bash) -> /mnt/c/...
        # (WSL mount) so wsl.exe can re-run it by absolute path. \L
        # lowercases the drive letter (GNU sed ships with Git Bash).
        wsl_script="$(printf '%s' "${script_dir}" | sed -E 's#^/([A-Za-z])/#/mnt/\L\1/#')/run-lint-ansible.sh"
        # MSYS2 rewrites /-leading args into Windows paths when launching a
        # Windows .exe, which would corrupt the /mnt path; disable that for
        # the exec so wsl.exe sees it verbatim.
        export MSYS2_ARG_CONV_EXCL='*'
        export MSYS_NO_PATHCONV=1
        exec wsl.exe -- bash "${wsl_script}"
        ;;
    *)
        # WSL ("Linux" uname) or native-Linux CI: the venv is reachable, so
        # run in place.
        ;;
esac

# Resolve the Common-Ansible substrate sibling - its shared controller venv,
# its bundled ansible-lint helper/config, and its substrate roles/ all hang
# off this one root. COMMON_ANSIBLE_ROOT overrides the sibling-checkout
# default.
# shellcheck source=hyper-v/ubuntu/Ansible/ops/imports/_common-ansible-root.sh
source "${repo_root}/hyper-v/ubuntu/Ansible/ops/imports/_common-ansible-root.sh"

venv_activate="${common_ansible_root}/.venv/bin/activate"
if [[ ! -f "${venv_activate}" ]]; then
    echo "::notice::no shared Common-Ansible controller venv at ${common_ansible_root}/.venv - run ops/bootstrap-controller.{ps1,sh}; skipping ansible-lint"
    exit 0
fi

# Activate (not python-invoke) so the helper's bare `ansible-lint`, and the
# `ansible-config` it execs, resolve from the shared venv. The activate script
# touches PS1, which `set -u` would flag as unbound, so relax -u across it.
set +u
# shellcheck source=/dev/null  # runtime path, generated by the bootstrap
source "${venv_activate}"
set -u

# Put the substrate roles/ on the path so the composer playbook's static
# import_roles resolve at syntax-check (see the composer-resolution note in
# the header). Substrate-only: this repo has no roles/ to lead the path.
export ANSIBLE_ROLES_PATH="${common_ansible_root}/roles"

# Lint THIS repo's root (its shim activates the gate); the helper and its
# bundled production config come from the substrate.
exec bash "${common_ansible_root}/.github/actions/ansible-lint/ansible-lint.sh" "${repo_root}"
